### ISSUE TITLE
Display backlight is adjustable without Google's kernels

### ISSUE THREAD

**Issue by doowzs** [yusefnapora/pixelbook-linux#19]
Hi, I am a Pixelbook user and I cannot appreciate your detailed instruction and scripts more. One thing that bothers me for a long time is that I can only adjust backlight in Google's 4.4 kernel, which is out-of-date from my perspective.

However, today I happened to find that the backlight is adjustable in latest kernels with the command-line interface (unfortunately not with GUI controls).

Laptop: i5 8+256
Distro: KUbuntu 19.04
DE: KDE Plasma (DE's config won't change brightness)
Kernel: 5.0.0-20-generic

I first find the display using `xrandr -q | grep connected`, which in my case is called `eDP-1`. Then I can adjust the brightness like `xrandr --output eDP-1 --brightness 0.3`, where the value of brightness goes from 0.0 to 1.0.

By `strace`-ing `xrandr`'s behaviour, it seems pretty tricky because `xrandr` uses direct I/O interaction to adjust the backlight instead of writing the brightness value into a system config file. I don't know the exact reason behind this, but if this method works for everyone, we can write scripts to adjust backlight and bind them to keyboard shortcuts :D.

**Comment by duckunix** [comment]
@doowzs - What about sound, networking, and input?  All those working in the later kernels?

**Comment by doowzs** [comment]
Well, I learned that `xrandr` is just dimming the content instead of adjusting the hardware brightness :disappointed:

@duckunix cras-server would crash on non-Google kernels so there is no audio except using bluetooth.

Everything else seems to work perfectly.

![Screenshot_20190720_120450](https://user-images.githubusercontent.com/33089028/61582960-9fb2b580-aae6-11e9-8c5d-4242ca4b95a5.png)

**Comment by valpackett** [comment]
hi, I've investigated the brightness issue:
https://github.com/EmbeddedAndroid/linux-eve/issues/2#issuecomment-529470238
