### ISSUE TITLE
Can't get past "OS Verification is OFF" after Ubuntu 19.1 install

### ISSUE THREAD

**Issue by joe-cormier** [yusefnapora/pixelbook-linux#24]
I made it through the install step and when restarting the Pixelbook it took me to the "OS verification is OFF" page.  I tried reinstalling Ubuntu again with no luck.  I've search for help but couldn't find a similar issue.  

Edit - I also tried starting out with 19.04 first and got stuck at the same point so maybe I missed something in the tutorial.  I tried using the google repair tool to fix the original OS with no luck.

**Comment by mcdowellmountains** [comment]
Have we determined if 19.1 will work if we rerun the install script after
upgrading from 19.04?  I have wanted to do this also, but have been
hesitant to proceed until knowing more.

John Longobardo
480-748-9530

**Comment by joe-cormier** [comment]
I was able to use the google repair tool and fixed the original OS.  I tried the tutorial again using 19.04 and it worked fine.  Then, upgraded to 19.1 and everything seems to be working great.  Thanks for the quick response to my comment and thanks for the awesome tutorial.
