### ISSUE TITLE
disk, dsm, kbl-rt5514-hotword-support and touch not found in the recovery image

### ISSUE THREAD

**Issue by MoeMod** [yusefnapora/pixelbook-linux#3]
![IMG_1126](https://user-images.githubusercontent.com/37328384/57868992-967f4100-7836-11e9-9683-a8c5a0cb870d.JPG)

**Comment by MoeMod** [comment]
BTW, I am using chrx without unlocked UEFI. Is this only work with UEFI firmware?

**Comment by yusefnapora** [comment]
Thanks for the report - I've only tested it with full UEFI firmware. It looks like it might be mounting the recovery image to a different device than the script expects.

You could try cd'ing into `/opt/eve-linux-setup` - there's a `recovery_mnt` directory there that should contain the recovery image files. If `/opt/eve-linux-setup/recovery_mnt` is empty, you can try mounting the image manually.

Mounting the image works like this:

```bash
# become root
sudo su
cd /opt/eve-linux-setup

# mount the partitions from the recovery image to loopback devices
kpartx -av chromeos_11647.154.0_eve_recovery_stable-channel_mp.bin

# You should see some output with a bunch of `loopX` device names. 
# You want the one that ends with `p3`, for example `loop0p3`. 
# Once you find the right loopback device, you can mount it

mount -t ext2 -o ro /dev/mapper/$device_name_from_above /opt/eve-linux-setup/recovery_mnt
```

If that works, there should be some files in the `recovery_mnt` dir afterwards, and re-running the ansible script should (hopefully) work.

Let me know if that helps at all; I'd like to get this working for dual-boot users also, but I don't have time right now to test myself.

**Comment by MoeMod** [comment]
After this error and reboot, it seems that ubuntu crashes and enters emergency mode.
I reinstalled ubuntu with chrx and ran the script again and got the same result. 
However, those files in /opt/eve-linux-setup/recovery_mnt are already mounted and not missing.
So... nothing to do but wating for my debug cable 😂

**Comment by MoeMod** [comment]
Now I get my debug cable and everything goes well now.
Thank you for your detailed instructions!

**Comment by hqzfj** [comment]
> ![IMG_1126](https://user-images.githubusercontent.com/37328384/57868992-967f4100-7836-11e9-9683-a8c5a0cb870d.JPG)

**Comment by hqzfj** [comment]
# #k

**Comment by hqzfj** [comment]
``
