### ISSUE TITLE
ls /dev/tty* not enumerating USB devices

### ISSUE THREAD

**Issue by uninc** [yusefnapora/pixelbook-linux#33]
when a USB device is plugged in , it is recognized via `dmesg` and also under `lsusb`

however `ls /dev/tty*` does not create any usb serial devices. 

therefore cannot communicate with the SuzyQ cable w adapter 

any ideas? chromeOS is up to date

**Comment by flantel** [comment]
I presume you are still in Chrome OS. Did you try flipping the usb-c end the other way around? Apparently the suziq is not symmetrical

**Comment by uninc** [comment]
> I presume you are still in Chrome OS. Did you try flipping the usb-c end the other way around? Apparently the suziq is not symmetrical
Also presume that I can read and follow instructions

**Comment by uninc** [comment]
Can someone help clarify on how to install this rule; I believe this to be what is causing the USB failing to enumerate in /dev/tty:

> There is a udev rules file, extra/usb_serial/51-google-serial.rules that should be installed in /etc/udev/rules.d/ and udev should be told to reread its rules. This rules file can be installed using the extra/usb_serial/install script.

[https://github.com/coreboot/chrome-ec/blob/master/docs/case_closed_debugging.md](url) 
after reading thru this:
[https://chromium.googlesource.com/chromiumos/platform/ec/+show/master/docs/case_closed_debugging.md](url)
udev files must be installed incorrectly or need to be reread ?

**Comment by uninc** [comment]
issue resolved. 

Linux (beta) files needed to be installed via settings before CR50 cable was recognised and enumerated in CROSH shell.
