### ISSUE TITLE
Ubuntu 19.10 - Failed step: Find mapper device to use for mounting image 

### ISSUE THREAD

**Issue by ghost** [yusefnapora/pixelbook-linux#37]
I have a fresh install of Ubuntu 19.10 and I receive the following error on the "Find mapper device to use for mounting image" step:

TASK [eve-recovery-files : Find mapper device to use for mounting image] *******
fatal: [localhost]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ kpartx_output.stdout | regex_search(regexp, '\\\\1') | first }}): 'NoneType' object is not iterable"}

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=1    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

**Comment by daemonp** [comment]
Check out PR #4 if you make that regex change locally it should work until it gets merged.

**Comment by ghost** [comment]
Thanks!

**Comment by mcdowellmountains** [comment]
Same issue, but making the change recommended does not work for me. Ubuntu
19.10

**Comment by ghost** [comment]
Have you tried this fork? 
https://github.com/flantel/pixelbook-linux

**Comment by daemonp** [comment]
> Have you tried this fork?
> https://github.com/flantel/pixelbook-linux

Yep, it's got all the latest changes

**Comment by mcdowellmountains** [comment]
What is the easiest way to upgrade to the new Kernel that you can suggest?
thx



Regards,

[image: Picture]

John Longobardo
480-748-9530 (m)
