### ISSUE TITLE
cras build fails on clean install of 19.10

### ISSUE THREAD

**Issue by dantrevino** [yusefnapora/pixelbook-linux#56]
While testing with 19.10, I did a clean build, then attempted to run the script.  cras build fails with the following:

TASK [eve-audio : build cras] **************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["make"], "delta": "0:00:00.280457", "end": "2020-05-25 22:37:26.004560", "msg": "non-zero return code", "rc": 2, "start": "2020-05-25 22:37:25.724103", "stderr": "server/cras_rclient.c: In function ‘cras_rclient_message_from_client’:\nserver/cras_rclient.c:628:6: error: taking address of packed member of ‘struct cras_config_global_remix’ may result in an unaligned pointer value [-Werror=address-of-packed-member]\n  628 |     m->coefficient);\n      |     ~^~~~~~~~~~~~~\ncc1: all warnings being treated as errors\nmake[1]: *** [Makefile:5031: server/libcrasserver_la-cras_rclient.lo] Error 1\nmake: *** [Makefile:459: all-recursive] Error 1", "stderr_lines": ["server/cras_rclient.c: In function ‘cras_rclient_message_from_client’:", "server/cras_rclient.c:628:6: error: taking address of packed member of ‘struct cras_config_global_remix’ may result in an unaligned pointer value [-Werror=address-of-packed-member]", "  628 |     m->coefficient);", "      |     ~^~~~~~~~~~~~~", "cc1: all warnings being treated as errors", "make[1]: *** [Makefile:5031: server/libcrasserver_la-cras_rclient.lo] Error 1", "make: *** [Makefile:459: all-recursive] Error 1"], "stdout": "Making all in src\nmake[1]: Entering directory '/opt/eve-linux-setup/adhd/cras/src'\n/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DPACKAGE_NAME=\\\"cras\\\" -DPACKAGE_TARNAME=\\\"cras\\\" -DPACKAGE_VERSION=\\\"0.1\\\" -DPACKAGE_STRING=\\\"cras\\ 0.1\\\" -DPACKAGE_BUGREPORT=\\\"dgreid@chromium.org\\\" -DPACKAGE_URL=\\\"http://www.chromium.org/\\\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\\\".libs/\\\" -DHAVE_LIBASOUND=1 -DALSA_PLUGIN_DIR=\\\"/usr/local/lib/alsa-lib\\\" -DCRAS_CONFIG_FILE_DIR=\\\"/usr/local/etc/cras\\\" -DCRAS_SOCKET_FILE_DIR=\\\"/var/run/cras\\\" -DHAVE_SSE42=1 -DHAVE_AVX=1 -DHAVE_AVX2=1 -DHAVE_FMA=1 -I.  -O2 -Wall -Werror -Wno-error=cpp -I../src/common -I../src/dsp -I../src/server -I../src/server/config      -I/usr/include/iniparser -MT server/libcrasserver_la-cras_rclient.lo -MD -MP -MF server/.deps/libcrasserver_la-cras_rclient.Tpo -c -o server/libcrasserver_la-cras_rclient.lo `test -f 'server/cras_rclient.c' || echo './'`server/cras_rclient.c\nlibtool: compile:  gcc -DPACKAGE_NAME=\\\"cras\\\" -DPACKAGE_TARNAME=\\\"cras\\\" -DPACKAGE_VERSION=\\\"0.1\\\" \"-DPACKAGE_STRING=\\\"cras 0.1\\\"\" -DPACKAGE_BUGREPORT=\\\"dgreid@chromium.org\\\" -DPACKAGE_URL=\\\"http://www.chromium.org/\\\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\\\".libs/\\\" -DHAVE_LIBASOUND=1 -DALSA_PLUGIN_DIR=\\\"/usr/local/lib/alsa-lib\\\" -DCRAS_CONFIG_FILE_DIR=\\\"/usr/local/etc/cras\\\" -DCRAS_SOCKET_FILE_DIR=\\\"/var/run/cras\\\" -DHAVE_SSE42=1 -DHAVE_AVX=1 -DHAVE_AVX2=1 -DHAVE_FMA=1 -I. -O2 -Wall -Werror -Wno-error=cpp -I../src/common -I../src/dsp -I../src/server -I../src/server/config -I/usr/include/iniparser -MT server/libcrasserver_la-cras_rclient.lo -MD -MP -MF server/.deps/libcrasserver_la-cras_rclient.Tpo -c server/cras_rclient.c  -fPIC -DPIC -o server/.libs/libcrasserver_la-cras_rclient.o\nmake[1]: Leaving directory '/opt/eve-linux-setup/adhd/cras/src'", "stdout_lines": ["Making all in src", "make[1]: Entering directory '/opt/eve-linux-setup/adhd/cras/src'", "/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DPACKAGE_NAME=\\\"cras\\\" -DPACKAGE_TARNAME=\\\"cras\\\" -DPACKAGE_VERSION=\\\"0.1\\\" -DPACKAGE_STRING=\\\"cras\\ 0.1\\\" -DPACKAGE_BUGREPORT=\\\"dgreid@chromium.org\\\" -DPACKAGE_URL=\\\"http://www.chromium.org/\\\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\\\".libs/\\\" -DHAVE_LIBASOUND=1 -DALSA_PLUGIN_DIR=\\\"/usr/local/lib/alsa-lib\\\" -DCRAS_CONFIG_FILE_DIR=\\\"/usr/local/etc/cras\\\" -DCRAS_SOCKET_FILE_DIR=\\\"/var/run/cras\\\" -DHAVE_SSE42=1 -DHAVE_AVX=1 -DHAVE_AVX2=1 -DHAVE_FMA=1 -I.  -O2 -Wall -Werror -Wno-error=cpp -I../src/common -I../src/dsp -I../src/server -I../src/server/config      -I/usr/include/iniparser -MT server/libcrasserver_la-cras_rclient.lo -MD -MP -MF server/.deps/libcrasserver_la-cras_rclient.Tpo -c -o server/libcrasserver_la-cras_rclient.lo `test -f 'server/cras_rclient.c' || echo './'`server/cras_rclient.c", "libtool: compile:  gcc -DPACKAGE_NAME=\\\"cras\\\" -DPACKAGE_TARNAME=\\\"cras\\\" -DPACKAGE_VERSION=\\\"0.1\\\" \"-DPACKAGE_STRING=\\\"cras 0.1\\\"\" -DPACKAGE_BUGREPORT=\\\"dgreid@chromium.org\\\" -DPACKAGE_URL=\\\"http://www.chromium.org/\\\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\\\".libs/\\\" -DHAVE_LIBASOUND=1 -DALSA_PLUGIN_DIR=\\\"/usr/local/lib/alsa-lib\\\" -DCRAS_CONFIG_FILE_DIR=\\\"/usr/local/etc/cras\\\" -DCRAS_SOCKET_FILE_DIR=\\\"/var/run/cras\\\" -DHAVE_SSE42=1 -DHAVE_AVX=1 -DHAVE_AVX2=1 -DHAVE_FMA=1 -I. -O2 -Wall -Werror -Wno-error=cpp -I../src/common -I../src/dsp -I../src/server -I../src/server/config -I/usr/include/iniparser -MT server/libcrasserver_la-cras_rclient.lo -MD -MP -MF server/.deps/libcrasserver_la-cras_rclient.Tpo -c server/cras_rclient.c  -fPIC -DPIC -o server/.libs/libcrasserver_la-cras_rclient.o", "make[1]: Leaving directory '/opt/eve-linux-setup/adhd/cras/src'"]}

PLAY RECAP *********************************************************************
localhost                  : ok=27   changed=10   unreachable=0    failed=1    skipped=4    rescued=0    ignored=0

**Comment by flantel** [comment]
cras does not like gcc9 which ships with 19.10 - you need to install gcc8 and set env vars to use it

**Comment by dantrevino** [comment]
Thanks @flantel!  I ended up using your patched version due to other issues later, and it worked great.

Thanks!
