### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by ranalabs** [yusefnapora/pixelbook-linux#9]
Hi, I'm getting this error when running the script. Any ideas on what to do to fix it? Thank you!

TASK [eve-recovery-files : Find mapper device to use for mounting image] *******
fatal: [localhost]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ kpartx_output.stdout | regex_search(regexp, '\\\\1') | first }}): 'NoneType' object is not iterable"}

**Comment by flantel** [comment]
Yes, see my pull request for a fix. Quite simple to do manually

**Comment by ranalabs** [comment]
Perfect - that did it! One small + and we're good to go. Thanks...

**Comment by mr-sk** [comment]
Helped me too - Can the maintainer please accept the PR. (Thanks @flantel)
